server {
    listen 80;
    server_name localhost;

    location /health {
        access_log off;
        default_type text/plain;
        return 200 'ok';
    }

    location / {
        default_type text/plain;
        return 200 'jsmedicine infrastructure is ready';
    }
}
